alias ls='ls -laGFh'
alias ping='ping -c 4'
alias rm=trash
alias vim=nvim
alias python="$(pyenv which python)"
alias pip="$(pyenv which pip)"
alias cat=bat
alias zshconfig='$(echo $EDITOR) $HOME/.zshrc && zshsource'
alias zshalias='$(echo $EDITOR) $ZSH_CUSTOM/aliases.zsh && zshsource'
alias zshsource='source $HOME/.zshrc && echo "Reloaded zsh config!"'
